---
title: "project_3_markdown_testing"
author: "Demetrios Samaras"
date: "2023-07-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE)
```


```{r library}
library(shiny)
library(tidyverse)
library(caret)
library(DT)
library(ggplot2)
library(shinydashboard)
library(randomForest)

```


```{r read cancer data }

cancer<- read.csv("wdbc.data") %>% as_tibble()

colnames(cancer)<- c("ID", "Diagnosis", "mean radius", "mean texture", "mean perimeter", "mean area", "mean smoothness", "mean compactness", "mean concavity", "mean concave points", "mean symmetry", "mean fractal dimension", "radius SE", "texture SE", "perimeter SE", "area SE", "smoothness SE", "compactness SE", "concavity SE", "concave points SE", "symmetry SE", "fractal dimension SE", "worst radius", "worst texture", "worst perimeter", "worst area", "worst smoothness", "worst compactness", "worst concavity", "worst concave points", "worst symmetry", "worst fractal dimension" )

```

```{r read abalone data }

abalone <- read.csv("ST558_project_3_app/abalone.data") %>% as_tibble 

colnames(abalone) <- c("Sex", "Length", "Diameter", "Height", "Whole_weight", "Shucked_weight", "Viscera_weight",  "Shell_weight", "Rings" )

```

```{r}

g <- ggplot(data=abalone, aes(x= Whole_weight, y=Rings))
g+ geom_point(aes(color= Sex)) + geom_smooth(method = "lm") + ggtitle("scatterplot")

```

```{r}

h <- ggplot(data = abalone, aes(x= Sex, y= Rings))
h+ geom_boxplot(aes(color=Sex))
```

```{r}

set.seed(13) 
        train <- sample(1:nrow(abalone), size = nrow(abalone)*.7)
        test <- setdiff(1:nrow(abalone), train)
        
        # training and testing subsets
        abalone_train <- abalone[train, ]
        abalone_test <- abalone[test, ]
        
        linear_model_1 <- train(Rings ~ Length + Diameter , 
                                data = abalone_train,
                                 method = "lm",
                                 preProcess = c("center", "scale"),
                                 trControl = trainControl(method = "cv", 
                                                          number = 5))

        predict(linear_model_1, newdata = data.frame("Length"=.665,"Diameter"=.525, "Sex"=NULL))
```





